In [2]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [8]:
df = pd.read_csv('jester-data-1.csv', header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,74,-7.82,8.79,-9.66,-8.16,-7.52,-8.50,-9.85,4.17,-8.98,...,2.82,99.00,99.00,99.00,99.00,99.00,-5.63,99.00,99.00,99.00
1,100,4.08,-0.29,6.36,4.37,-2.38,-9.66,-0.73,-5.34,8.88,...,2.82,-4.95,-0.29,7.86,-0.19,-2.14,3.06,0.34,-4.32,1.07
2,49,99.00,99.00,99.00,99.00,9.03,9.27,9.03,9.27,99.00,...,99.00,99.00,99.00,9.08,99.00,99.00,99.00,99.00,99.00,99.00
3,48,99.00,8.35,99.00,99.00,1.80,8.16,-2.82,6.21,99.00,...,99.00,99.00,99.00,0.53,99.00,99.00,99.00,99.00,99.00,99.00
4,91,8.50,4.61,-4.17,-5.39,1.36,1.60,7.04,4.61,-0.44,...,5.19,5.58,4.27,5.19,5.73,1.55,3.11,6.55,1.80,1.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24978,100,0.44,7.43,9.08,2.33,3.20,6.75,-8.79,-0.53,-8.74,...,8.83,-1.21,9.22,-6.70,8.45,9.03,6.55,8.69,8.79,7.43
24979,91,9.13,-8.16,8.59,9.08,0.87,-8.93,-3.50,5.78,-8.11,...,-1.17,-5.73,-1.46,0.24,9.22,-8.20,-7.23,-8.59,9.13,8.45
24980,39,99.00,99.00,99.00,99.00,-7.77,99.00,6.70,-6.75,99.00,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
24981,37,99.00,99.00,99.00,99.00,-9.71,99.00,4.56,-8.30,99.00,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
24982,72,2.43,2.67,-3.98,4.27,-2.28,7.33,2.33,4.56,6.75,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00

In [9]:
df = df.replace(99, np.nan)
df = df.drop(columns=[0])
df

,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,100
0,-7.82,8.79,-9.66,-8.16,-7.52,-8.50,-9.85,4.17,-8.98,-4.76,...,2.82,NaN,NaN,NaN,NaN,NaN,-5.63,NaN,NaN,NaN
1,4.08,-0.29,6.36,4.37,-2.38,-9.66,-0.73,-5.34,8.88,9.22,...,2.82,-4.95,-0.29,7.86,-0.19,-2.14,3.06,0.34,-4.32,1.07
2,NaN,NaN,NaN,NaN,9.03,9.27,9.03,9.27,NaN,NaN,...,NaN,NaN,NaN,9.08,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,8.35,NaN,NaN,1.80,8.16,-2.82,6.21,NaN,1.84,...,NaN,NaN,NaN,0.53,NaN,NaN,NaN,NaN,NaN,NaN
4,8.50,4.61,-4.17,-5.39,1.36,1.60,7.04,4.61,-0.44,5.73,...,5.19,5.58,4.27,5.19,5.73,1.55,3.11,6.55,1.80,1.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24978,0.44,7.43,9.08,2.33,3.20,6.75,-8.79,-0.53,-8.74,7.23,...,8.83,-1.21,9.22,-6.70,8.45,9.03,6.55,8.69,8.79,7.43
24979,9.13,-8.16,8.59,9.08,0.87,-8.93,-3.50,5.78,-8.11,4.90,...,-1.17,-5.73,-1.46,0.24,9.22,-8.20,-7.23,-8.59,9.13,8.45
24980,NaN,NaN,NaN,NaN,-7.77,NaN,6.70,-6.75,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24981,NaN,NaN,NaN,NaN,-9.71,NaN,4.56,-8.30,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24982,2.43,2.67,-3.98,4.27,-2.28,7.33,2.33,4.56,6.75,4.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print(df.iloc[3, 2])

nan

In [12]:
jokes_means = pd.DataFrame(data=np.nanmean(df.values, axis=0).reshape(1,-1), index=['mean'], columns=np.arange(1, df.shape[1]+1))
jokes_means

,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,100
mean,0.904573,0.20846,0.316574,-1.449114,0.403556,1.594447,-0.429662,-0.624085,-0.557031,1.301231,...,2.038527,1.179744,2.504041,1.173482,1.03913,1.528003,1.67375,0.767692,-0.031244,1.354711

In [17]:
# Question #6
df.iloc[15827, 79]

-1.99

In [45]:
# Question #7
movie_items = pd.read_excel('movies_latent_factors.xlsx', sheet_name='Items')
movie_items

,Movie ID,Title,Factor1,Factor2,Factor3,Factor4,Factor5,Factor6,Factor7,Factor8,Factor9,Factor10,Factor11,Factor12,Factor13,Factor14,Factor15
0,11,Star Wars: Episode IV - A New Hope (1977),-1.521848,-1.038507,2.027269,0.247933,-0.594548,2.513260,-1.848910,0.476710,-0.224146,-0.760681,-0.973915,0.862379,0.403861,1.129616,-0.248806
1,12,Finding Nemo (2003),-0.342185,-0.296586,-0.385962,2.443297,-1.097015,-0.619465,0.572887,0.329516,-0.712228,0.323554,-0.561948,-0.142405,-0.564415,0.506876,1.274993
2,13,Forrest Gump (1994),-2.240888,-0.438815,-2.275177,0.614548,0.904469,0.711919,-0.420876,1.302036,-0.868418,-0.160122,0.633667,0.133138,-0.330276,-2.209004,-0.419092
3,14,American Beauty (1999),-0.634531,2.186059,-0.066681,0.086197,0.517558,-0.185319,-0.412352,0.063841,0.075937,-0.577682,0.526803,-1.465557,-0.819682,0.549010,-0.681191
4,22,Pirates of the Caribbean: The Curse of the Bla...,0.517348,-1.456763,0.369161,0.073903,-0.098332,-0.594722,0.828888,0.033626,-0.707414,0.717877,1.394326,-0.786986,1.429191,0.855746,-2.292566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,9806,The Incredibles (2004),0.159967,-0.051123,0.311183,1.841867,-1.952736,-0.836041,0.639252,-0.413082,-0.310868,0.448225,-0.846044,-0.158192,-0.649164,0.045580,1.017861
96,10020,Beauty and the Beast (1991),1.286288,0.004957,-0.157640,2.579640,-0.042687,-0.256582,-0.007971,0.458163,0.091394,0.323339,-0.862833,-0.508185,0.994535,0.868700,-0.487076
97,36657,X-Men (2000),0.811901,-0.893280,0.668953,-0.885074,-1.070468,-0.973154,-0.037449,-0.925609,-0.122112,-0.328822,-0.163103,-0.307299,0.642105,-1.355542,0.067790
98,36658,X2: X-Men United (2003),1.161006,-0.715613,0.712633,-0.688808,-0.717785,-1.007047,-0.267268,-0.802322,-0.249239,-0.540419,-0.291422,-0.240216,0.290714,-1.217250,-0.288130
99,36955,True Lies (1994),1.734008,0.265436,-0.003391,-0.491754,-0.322739,0.850165,-0.150377,-0.075895,1.373386,0.934767,0.489299,-0.062678,0.333703,-0.223382,-0.022599

In [46]:
# Question #9
movie_users = pd.read_excel('movies_latent_factors.xlsx', sheet_name='Users')
movie_users

,User,Factor1,Factor2,Factor3,Factor4,Factor5,Factor6,Factor7,Factor8,Factor9,Factor10,Factor11,Factor12,Factor13,Factor14,Factor15
0,4768,-0.204024,0.161079,-0.090447,0.138495,-0.162934,0.163894,0.051502,-0.088582,0.126829,0.065967,0.085008,0.355404,0.007108,-0.118663,-0.039125
1,156,-0.189652,-0.178979,-0.091490,-0.000823,-0.032646,0.177209,-0.098123,-0.068283,-0.011575,0.120866,-0.009931,-0.048606,0.045916,0.113671,0.179873
2,5323,-0.115308,-0.090886,-0.053129,0.018472,-0.068081,-0.004828,0.113005,0.102107,0.034758,0.000693,-0.073712,-0.019460,0.108372,0.054471,-0.109552
3,174,-0.227462,-0.272532,-0.017231,0.054324,0.214755,-0.072639,-0.033122,-0.086508,-0.131479,0.180403,0.095890,-0.082396,0.036767,-0.165438,0.050692
4,4529,-0.014616,-0.102218,-0.107935,0.155784,-0.123362,-0.118228,-0.013549,-0.050622,0.058698,-0.159600,-0.142382,-0.132836,-0.039897,0.129063,0.102669
5,783,-0.020301,-0.031919,-0.036955,0.033690,0.000174,-0.003178,0.054474,0.045424,-0.053308,0.003437,-0.041750,0.059725,-0.021647,0.039873,-0.061857
6,3878,-0.091462,0.215879,-0.180453,0.085408,-0.321094,0.227947,0.053767,0.038017,0.097141,-0.139872,0.029253,0.214467,0.189250,0.065990,0.102776
7,768,0.000819,-0.009229,-0.019228,0.002703,0.012869,0.006655,0.007687,0.018747,0.014705,-0.009256,-0.010116,-0.010051,-0.002108,0.043223,-0.006670
8,4469,-0.030528,-0.011537,-0.042822,-0.014378,0.031338,0.012297,-0.000038,-0.010264,-0.006781,-0.019950,-0.014435,0.010926,0.024400,0.005318,-0.007983
9,1882,-0.083093,-0.029160,0.013748,0.022716,-0.062732,-0.080670,-0.019723,0.013253,-0.091305,-0.090687,0.030638,-0.113364,-0.021325,0.181508,0.022357
10,4997,-0.185443,-0.276496,-0.781275,-0.240506,0.029611,-0.271814,-0.056266,-0.111825,-0.290910,-0.255087,-0.098079,0.103116,-0.100563,0.100164,0.043196
11,2067,-0.083242,0.181171,-0.344267,-0.019713,-0.243199,0.039220,-0.092086,0.114808,-0.036472,0.042386,-0.186812,-0.127038,0.176661,-0.055812,-0.000042
12,3806,-0.042344,-0.040755,-0.055720,-0.073726,0.018203,0.091940,0.123959,-0.157403,-0.020388,0.082493,0.223057,-0.040915,-0.130308,-0.021816,0.034549
13,2848,-0.113283,-0.098942,-0.040393,0.042180,-0.041068,-0.039568,0.018291,-0.191254,0.218912,0.017262,-0.087468,0.036894,0.067105,-0.016780,-0.029503
14,4433,-0.298760,-0.290228,-0.160120,0.156277,-0.055364,-0.434205,-0.089259,0.252211,-0.107413,-0.088591,0.121157,0.071371,-0.415598,-0.022139,-0.183021
15,3519,-0.068454,0.020090,0.039336,0.002958,-0.018140,0.006501,-0.108526,0.025045,0.056334,-0.031291,-0.035533,0.005171,0.005546,0.020780,-0.023623
16,5338,-0.061259,0.014661,0.011412,0.001727,0.064996,-0.078448,0.059510,0.017402,-0.040234,-0.073409,-0.016323,0.031774,-0.062413,0.107708,0.065081
17,3947,-0.022340,-0.115285,-0.136980,0.038593,-0.003029,0.071770,-0.146675,-0.285724,-0.044472,-0.054032,0.064019,-0.045329,-0.111919,0.066313,0.002395
18,4373,-0.136550,-0.089406,-0.235399,0.120585,-0.168168,0.129990,-0.035084,-0.324028,0.087531,0.045290,0.207850,-0.028972,-0.175184,-0.058283,0.147797
19,2092,-0.121763,0.011065,-0.037121,0.032568,0.017570,0.095802,0.120238,-0.048410,0.008829,0.121778,0.093783,0.044754,-0.003087,0.164487,-0.075231
20,525,-0.040290,0.014383,-0.098967,-0.018957,0.012388,0.035546,0.000903,0.012835,-0.021080,0.018742,-0.050483,-0.025394,0.034079,0.038330,-0.001341
21,4327,0.008227,0.073899,-0.323967,0.131203,-0.320862,0.054997,0.060751,0.162314,0.044612,-0.232241,0.094986,-0.106570,-0.051692,-0.093490,0.029534
22,3048,-0.320315,0.078290,-0.083182,-0.221577,-0.078184,-0.145306,-0.020166,0.124409,-0.063425,0.004726,0.009683,0.028016,-0.018100,-0.128452,0.069972
23,2665,-0.076167,-0.006064,-0.001902,-0.053641,0.021751,0.048207,-0.083980,0.146907,-0.057422,0.006085,0.063240,0.086562,-0.132328,0.146198,0.029200
24,4940,-0.113099,0.047643,-0.053024,0.024834,0.010643,-0.012051,-0.049150,0.006252,0.020429,0.004349,0.028372,0.010227,-0.008233,-0.029304,0.090511

In [39]:
user = movie_users.index[movie_users['User'] == 2665][0]
item = movie_items.index[movie_items['Movie ID'] == 788][0]
movie_users = movie_users.drop(columns='User').values
movie_items = movie_items.drop(columns=['Movie ID', 'Title']).values

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [40]:
user_preference = movie_users[2665]
item_preference = movie_items[788]
user_preference.dot(item_preference)

KeyError: 2665

In [41]:
user_preference = movie_users[156]
item_preference = movie_items[786]
user_preference.dot(item_preference)

KeyError: 156

In [42]:
value = movie_items.index[movie_items['Movie ID'] == 105][0]
movie_items.loc[value, 'Factor3']

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [44]:
user = movie_users.index[movie_users['User'] == 1882][0]
pred_scores = []
for mov in range(movie_items.shape[0]):
    user = movie_users.index[movie_users['User'] == 156][0]
    item = movie_items.index[movie_items['Movie ID'] == 786][0]
    movie_users = movie_users.drop(columns='User').values
    movie_items = movie_items.drop(columns=['Movie ID', 'Title']).values
    user_preference = movie_users[156]
    item_preference = movie_items[786]
    pred_score = user_preference.dot(item_preference)
    pred_scores.append(pred_score)
og_pred_scores = pd.DataFrame(data=pred_scores)
og_pred_scores

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [23]:
# Question #8
highest = movie_items['Factor11'].max()
value = movie_items.index[movie_items['Factor11'] == highest][0]
movie_items.loc[value, 'Movie ID']

671

In [15]:
# Best and worst jokes
best_joke_score = jokes_means.max(axis=1)[0]
best_joke = jokes_means.T.index[jokes_means.T['mean'] == best_joke_score][0]
worst_joke_score = jokes_means.min(axis=1)[0]
worst_joke = jokes_means.T.index[jokes_means.T['mean'] == worst_joke_score][0]
print('Best joke:', best_joke, '. With mean score:', best_joke_score)
print('Worst joke:', worst_joke, '. With mean score:', worst_joke_score)

Best joke: 50 . With mean score: 3.6650848950824924
Worst joke: 58 . With mean score: -3.8338796373689963

In [5]:
arr = df.values
print(arr.shape)

(11191, 101)

In [16]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

818450 (818450,)

In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)

In [35]:

arr[idx[0][0], idx[1][0]]

-5.15

In [36]:
new_arr[idx[0][0], idx[1][0]]

99.0